---
title: "Figure 1"
output: html_notebook
author: "Meng-Ching Ko (MaggieMCKO)"
date: "06/23/2022"
---

This [R Markdown](http://rmarkdown.rstudio.com) Notebook contain codes for reproducing Fig.2 and related supplement tables of Ko et al. (https://www.biorxiv.org/content/10.1101/2022.06.13.495861v1).

### Fig. 2D
```{r}
library(tidyverse) # v.1.3.0
library(lme4) # 1.1-29
library(arm) # 1.7-19
library(gridExtra) # 2.3
library(grid) # 4.1.2
set.seed(100)

## load data
path =  paste0(getwd(), "/Data/RNAscope_NormalizedStainedArea.tsv")
RNAscope = read_tsv(path)

probes = c("ALDH1A2", "AR", "HSD17B12", "SRD5A2", "UTS2B")
stats2 = lapply(probes, function(Probe_x){
  # Probe_x = probes[4]
  print(Probe_x)
  db = RNAscope %>% filter(Probe == Probe_x) 
  
  head(db)
  
  db$Group = factor(db$Group)
  db$Individual = factor(db$Individual)
  db$Slide = factor(db$Slide)
  
  db$Group <- droplevels(db$Group)
  db$Individual <- droplevels(db$Individual)
  db$Slide = droplevels(db$Slide)
  
  y_lab = "Normalized stained area (%)"
  
  # 1. deciding using sqrt or not and evaluating model
  mod_a <- lmer(data = db, log(percent_area_slide) ~ Group + (1|Slide) ) # log
  
  plot(mod_a)  
  summary(mod_a)
  
  dev.off()
  par(mfrow=c(3,2))
  qqnorm(resid(mod_a))
  qqline(resid(mod_a))
  qqnorm(ranef(mod_a)$"Slide"[,1])   # random effect
  qqline(ranef(mod_a)$"Slide"[,1])
  scatter.smooth(fitted(mod_a), resid(mod_a))
  
  new_data_mod_a <- expand.grid(Group = levels(db$Group)) # fix effect
  xmat <- model.matrix(~ Group, data=new_data_mod_a)  # fix effect
  new_data_mod_a$fit <- xmat%*%fixef(mod_a)
  
  nsim <- 10000
  bsim <- arm::sim(mod_a, n.sim=nsim ) #simulation of the model 10000 times
  ## To get the mean estimate of the fixed effects parameters apply(bsim@fixef, 2, mean)
  apply(bsim@fixef, 2, mean)
  ## To get the 95% credible Interval estimate of the fixed effects parameters apply(bsim@fixef, 2, quantile, prob=c(0.025, 0.975))
  apply(bsim@fixef, 2, quantile, prob=c(0.025, 0.975))
  
  Ind_b_CrI = apply(bsim@fixef, 2, quantile, prob=c(0.025, 0.975)) 
  
  Ind_b = mod_a@beta
  x = as.data.frame(VarCorr(mod_a)); x
  Ind_random_Slide = x[1, 4]
  # Ind_random_Group = x[2, 4]
  Ind_residual = x[2, 4]
  Ind_random_Slide_CrI = quantile(apply(bsim@ranef$Slide[,,1],1,var),prob=c(0.025, 0.975))
  # Ind_random_Group_CrI = quantile(apply(bsim@ranef$n_Group[,,1],1,var),prob=c(0.025, 0.975))
  Ind_residual_CrI = quantile(bsim@sigma^2,c(0.025, 0.975))
  
  df_t = rbind(cbind("Var" = Probe_x, "Parameter" = levels(db$Group), 
                     "Estimate" = Ind_b, t(Ind_b_CrI)),
               cbind("Var" = Probe_x, "Parameter" = "random_Slide", 
                     "Estimate" =  Ind_random_Slide, t(Ind_random_Slide_CrI)),
               cbind("Var" = Probe_x, "Parameter" = "residual", 
                     "Estimate" =  Ind_residual, t(Ind_residual_CrI)))
  
  fitmat <- matrix(ncol=nsim, nrow=nrow(new_data_mod_a))
  for(i in 1:nsim) fitmat[,i] <- xmat %*% bsim@fixef[i,]    # fitted values
  new_data_mod_a$lower <- apply(fitmat, 1, quantile, prob=0.025)
  new_data_mod_a$upper <- apply(fitmat, 1, quantile, prob=0.975)
  new_data_mod_a$fit <- apply(fitmat, 1, mean)
  new_data_mod_a$fit_exp <- exp(new_data_mod_a$fit)        # transform back from log
  new_data_mod_a$upper_exp <- exp(new_data_mod_a$upper)    # transform back from log
  new_data_mod_a$lower_exp <- exp(new_data_mod_a$lower)    # transform back from log
  
  w = 0.25
  grey_point_size = 0.5
  mean_point_size = 1
  errorbar_wd = 1
  errorbar_hori = 0
  dodge = position_jitter(width = 0.05, height = 0)
  
  
  errorbar_col = "darkorange"
  
  plot_mod_a3 = ggplot(new_data_mod_a) +
    # need this layer to set up
    geom_point(data = new_data_mod_a,
               aes(x = Group, y = fit_exp), color='black', size=mean_point_size) +
    # raw data
    geom_point(data = db, 
               aes(x = as.numeric(Group)+w, y = percent_area_slide),
               position = dodge, alpha = 0.5, size = grey_point_size,
               color = "grey50") +
    # CI
    geom_errorbar(data = new_data_mod_a,
                  aes(x = Group, ymax = upper_exp, ymin = lower_exp),
                  width = errorbar_hori, size = errorbar_wd,
                  color = errorbar_col) +
    # estimate
    geom_point(data = new_data_mod_a,
               aes(x = Group, y = fit_exp), color='black', size=mean_point_size) +
    ylab(y_lab) +
    ggtitle(Probe_x) +
    theme_classic() + 
    theme(plot.title = element_text(hjust = 0.5)); plot_mod_a3
  
  pp = function(StimulatedTable){
    Dayn = 1:nrow(fitmat) # (row of fitmat)
    
    combi = combn(Dayn, 2)
    
    d = lapply(1:ncol(combi), function(combiN){
      # combiN = 1
      tmp = combi[, combiN]
      p = mean(fitmat[tmp[1],]<fitmat[tmp[2],])
      df = tibble("Group1" = (new_data_mod_a$Group[tmp[1]]), 
                  "Group2" = (new_data_mod_a$Group[tmp[2]]), "pp" = p)
    })
    
    dd = d %>% bind_rows() %>%
      mutate(`sig (2>1)` = ifelse(pp > 0.95, 'sig', NA))
    return(dd)
  }
  
  CI2 = Ind_b_CrI %>% t() %>% as.data.frame() %>% rownames_to_column
  df_t2 = df_t %>% as_tibble()
  
  return(list(plot_mod_a3, pp(new_data_mod_a), df_t2, CI2))
})
```
### Supplementary Table 2 and 3
#### CredibleInterval
```{r}
pp_CI2 = lapply(1:length(stats2), function(i){
  # i=1
  stats2[[i]][[4]] %>% bind_cols("Probe" = probes[i])
}) %>% bind_rows(); pp_CI2
```

#### estimates
```{r}
pp_est2 = lapply(1:length(stats2), function(i){
  # i=1
  stats2[[i]][[3]] %>% bind_cols("Probe" = probes[i])
}) %>% bind_rows(); pp_est2
```

#### PostProbability
```{r}
pp_summary2 = lapply(1:length(stats2), function(i){
  # i=1
  stats2[[i]][[2]] %>% bind_cols("Probe" = probes[i])
}) %>% bind_rows(); pp_summary2
```

#### Graph
```{r}
plots2 =  lapply(1:length(stats2), function(i){
  # i=1
  p = stats2[[i]][[1]] #
  p
}) 

```

```{r}
x = arrangeGrob(grobs = plots2, nrow = 1)
grid.draw(x)
```



### Fig. 2E
#### load data
```{r}
library(tidyverse) # v.1.3.1
library(gplots) # 3.1.3
library(RColorBrewer) # 1.1-3

set.seed(100)

## load data
path =  paste0(getwd(), "/Data/Expression.tsv")
Expr = read_tsv(path)

# make wide
Expr_s = Expr %>% pivot_wider(id_cols = c(GeneSymbol, description), 
                              names_from = Group, values_from = `LFC.ave`) 
```

#### prep matrix
```{r}
# target genes
targets = c("AR", "SRD5A2", "CYP19A1", "ESR1", "ESR2", "BDNF", "KDR", "FLT1", "FLT4", 
             "VEGFC", "VEGFA", "MMP2", "MMP9", "NTRK2", "NTRK1", "NGFR", 
             "UTS2B", "SULT1A1", "SULT1E1", "AKR1C2", "GPER1", "GPRC6A", 
             "SP8", "ABP", "SHBG", "HSD3B2", "CYP17A1", "HSD17B12", "SRD5A2", "SRD5A1", "SRD5A3", 
             "CYP19A1", "AKR1C4", "AKR1D1", "COMT",
             "HSD17B1", "HSD17B11", "HSD17B2", "HSD17B4", 
             "UGT1A1", "UGT1A8", "UGT1A9", "UGT2B17", 
             "ALDH1A2", "STAR", "TSPO", "VDAC1") 

# target genes expr
Expr_s_targets = Expr_s %>% filter(GeneSymbol %in% targets)

# prep matrix
input_matrix = Expr_s_targets[, 3:8] %>% as.matrix()
row.names(input_matrix) = paste0(Expr_s_targets$GeneSymbol, ": ", Expr_s_targets$description)
input_matrix[is.na(input_matrix)] = 0
```

#### prep annotations
```{r}
# color for expression
col_pl = rev(brewer.pal(11,"PuOr"))

#  color for annotation
hc = hclust(dist(input_matrix))
plot(hc)
str(hc)
hc_lab = hc$labels
hc_lab_sym = gsub("(.*): .*.$", "\\1", hc_lab); hc_lab_sym

## add annotation
sex_steriod_receptors = c("GPRC6A", "AR", "ESR1", "ESR2")
steroidogenesis = c("AKR1D1", "COMT", "CYP17A1",  "CYP19A1", 
                    "HSD17B1", "HSD17B11", "HSD17B12","HSD17B2",  "HSD17B4", "HSD3B2", 
                    "SRD5A1", "SRD5A2", "SRD5A3", "STAR", "SULT1E1", "TSPO", 
                    "UGT1A1", "UGT1A8", "UGT1A9", "UGT2B17", "VDAC1", "ALDH1A2")   
angio = c("FLT1", "FLT4", "KDR", "MMP2", "MMP9", "VEGFA", "VEGFC", "UTS2B")
neuro_recruit = c("BDNF", "NTRK2")

input_anno = sapply(hc_lab_sym , function(s){
  if(s%in% steroidogenesis){"Steroidogenesis"}else if(s %in% sex_steriod_receptors){
    "Sex steriod receptors"}else if (s%in%neuro_recruit){
      "Testosterone-induced neuronal recruitment"}else if(s %in% angio){
        "Testosterone-induced angiogenesis"}else{"SP8"}
})
length(input_anno) == nrow(input_matrix)

# display.brewer.pal(9, name = 'Set1')
colpal_anno = brewer.pal(9, name = 'Set1')[c(9, 2, 3, 1,6, 8, 7,4,5)]
colpal_anno = alpha(colpal_anno, alpha = 0.75)
colpal_anno = colpal_anno[1:length(unique(input_anno))]
plot(1:length(colpal_anno),  col = colpal_anno, cex = 3, pch = 19)
length(colpal_anno)
length(unique(input_anno))

funtobe = c("Steroidogenesis", "Sex steriod receptors", "Testosterone-induced neuronal recruitment",
            "Testosterone-induced angiogenesis", "SP8")
jColors <- data.frame(fun = funtobe, color = I(colpal_anno))
plot(1:length(jColors$color),  col = jColors$color, cex = 3, pch = 19)
RowSideColors_fun = jColors$color[match(input_anno, jColors$fun)]

```

#### heatmap
```{r}
par( lwd = 0.5)
heatmap.2(x = input_matrix, Rowv = T, Colv = F, dendrogram =  "row",
          col = col_pl,
          
          RowSideColors = RowSideColors_fun,
          na.rm = TRUE,
          na.color = "grey90",
          trace = "none",
          density.info = "none",
          key.title = "LFC",
          key.xlab = NA,
          key.ylab = "1",
          srtCol = 0,
          cexRow = 0.7,
          cexCol = 0.7,
          adjCol = 0.5,
          lmat = rbind(c(3, 1, 2, 0), c(5, 5, 5 ,4)), 
          lhei = c(.85, .15), 
          lwid = c(0.1, 0.03, 0.2, 0.8),
          margins =c(2, 2)
)

```
#### legend
```{r}
plot.new()
legend(x = 0.1, y = 0.9,      
       title = "Category",
       legend = jColors$fun, # category labels
       col = jColors$color,  # color key
       cex = 1, lty = 1,  # line style
       lwd = 5,          # line width,
       box.lwd = .1, 
       ncol = 1
) 
```

